#!/bin/bash

if [ ! -d ".venv" ]; then
    echo "Virtual environment '.venv' not found. Creating..."
    python3 -m venv .venv
    
    echo "Installing dependencies..."
    ./.venv/bin/pip install --upgrade pip
    ./.venv/bin/pip install pandas numpy torch timm opencv-python
    
    echo "Setup complete!"
else
    echo "Virtual environment '.venv' already exists."
	sleep 3
	clear
fi

source ./.venv/bin/activate && python3 main.py